from telegram.ext import Updater, CommandHandler
from flask import Flask, request
import json
import os

dir_path = os.path.dirname(os.path.realpath(__file__))
config_path = os.path.join(dir_path, 'config.json')

with open(config_path, 'r') as f:
    config = json.load(f)

app = Flask(__name__)

@app.route('/webhook', methods=['POST'])
def webhook():
    data = request.json
    if 'issue' in data:
        # Send issue content to Telegram group using Telegram API
        send_issue_to_telegram(data['issue'])
    return '', 200

Updater(token = config["TELEGRAM_BOT_TOKEN"], use_context = True)

def send_issue_to_telegram(issue):
    # Initialize the Telegram bot using the API token generated by BotFather
    bot = Updater(token = config["TELEGRAM_BOT_TOKEN"], use_context = True)

    # Set the chat ID of the Telegram group where you want to post the issue content
    chat_id = config["CHAT_ID"]

    # Construct the message to send to the Telegram group
    message = f"[Issue #{issue['number']} - {issue['title']}]({issue['html_url']}) \n\n{issue['body']}"

    # Use the bot to send the message to the Telegram group
    bot.bot.send_message(chat_id=chat_id, text=message, parse_mode='Markdown')

if __name__ == '__main__':
    app.run(debug=True)
